# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: time_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12time_service.proto\x12\x0btimeservice\"\r\n\x0bTimeRequest\"#\n\x0cTimeResponse\x12\x13\n\x0bserver_time\x18\x01 \x01(\t2S\n\x0bTimeService\x12\x44\n\rGetServerTime\x12\x18.timeservice.TimeRequest\x1a\x19.timeservice.TimeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'time_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TIMEREQUEST']._serialized_start=35
  _globals['_TIMEREQUEST']._serialized_end=48
  _globals['_TIMERESPONSE']._serialized_start=50
  _globals['_TIMERESPONSE']._serialized_end=85
  _globals['_TIMESERVICE']._serialized_start=87
  _globals['_TIMESERVICE']._serialized_end=170
# @@protoc_insertion_point(module_scope)
