# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import time_service_pb2 as time__service__pb2


class TimeServiceStub(object):
    """The time service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetServerTime = channel.unary_unary(
                '/timeservice.TimeService/GetServerTime',
                request_serializer=time__service__pb2.TimeRequest.SerializeToString,
                response_deserializer=time__service__pb2.TimeResponse.FromString,
                )


class TimeServiceServicer(object):
    """The time service definition.
    """

    def GetServerTime(self, request, context):
        """GetServerTime is a simple RPC that takes a TimeRequest and 
        returns a TimeResponse with the current server time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetServerTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerTime,
                    request_deserializer=time__service__pb2.TimeRequest.FromString,
                    response_serializer=time__service__pb2.TimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'timeservice.TimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimeService(object):
    """The time service definition.
    """

    @staticmethod
    def GetServerTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/timeservice.TimeService/GetServerTime',
            time__service__pb2.TimeRequest.SerializeToString,
            time__service__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
